/* jshint ignore:start */
var templates = {};
templates["page.frame"] = Handlebars.template({"1":function(container,depth0,helpers,partials,data,blockParams) {
    var stack1, alias1=container.lambda, alias2=container.escapeExpression;

  return "      <div id=\""
    + alias2(alias1((depth0 != null ? depth0.cid : depth0), depth0))
    + "\" data-options=\"header:'#a_header"
    + alias2(alias1((depth0 != null ? depth0.cid : depth0), depth0))
    + "',style:{marginBottom:'0px'}\" style=\"overflow:auto;padding:10px;background:#fafafa;\">\r\n        <div id=\"a_header"
    + alias2(alias1((depth0 != null ? depth0.cid : depth0), depth0))
    + "\" style=\"text-align:center\">\r\n          "
    + alias2(alias1((depth0 != null ? depth0.name : depth0), depth0))
    + "\r\n        </div>\r\n"
    + ((stack1 = helpers["if"].call(depth0 != null ? depth0 : (container.nullContext || {}),((stack1 = blockParams[0][0]) != null ? stack1.children : stack1),{"name":"if","hash":{},"fn":container.program(2, data, 0, blockParams),"inverse":container.noop,"data":data,"blockParams":blockParams})) != null ? stack1 : "")
    + "      </div>\r\n";
},"2":function(container,depth0,helpers,partials,data,blockParams) {
    var stack1;

  return ((stack1 = helpers.each.call(depth0 != null ? depth0 : (container.nullContext || {}),((stack1 = blockParams[1][0]) != null ? stack1.children : stack1),{"name":"each","hash":{},"fn":container.program(3, data, 1, blockParams),"inverse":container.noop,"data":data,"blockParams":blockParams})) != null ? stack1 : "");
},"3":function(container,depth0,helpers,partials,data,blockParams) {
    var stack1, alias1=container.lambda, alias2=container.escapeExpression;

  return "        <div class=\"menu_item\">\r\n          <a id=\""
    + alias2(alias1(((stack1 = blockParams[0][0]) != null ? stack1.cid : stack1), depth0))
    + "\" style=\"cursor: pointer;display: inline-block;text-align: center;\">\r\n            "
    + alias2(alias1(((stack1 = blockParams[0][0]) != null ? stack1.name : stack1), depth0))
    + "\r\n          </a>\r\n        </div>\r\n";
},"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data,blockParams) {
    var stack1;

  return "<div id=\"root\" class=\"easyui-layout\" style=\"width: 1366px;height:768px;\">\r\n  <!--页头-->\r\n  <div data-options=\"region:'north'\" style=\"height: 114px;border:false;\"></div>\r\n  <!--菜单栏-->\r\n  <div data-options=\"region:'west',split:true,minWidth:180,collapsible:true,width:180\">\r\n    <div id=\"t_menu\" data-options=\"fit:false\" class=\"easyui-accordion\">\r\n"
    + ((stack1 = helpers.each.call(depth0 != null ? depth0 : (container.nullContext || {}),(depth0 != null ? depth0.test : depth0),{"name":"each","hash":{},"fn":container.program(1, data, 1, blockParams),"inverse":container.noop,"data":data,"blockParams":blockParams})) != null ? stack1 : "")
    + "    </div>\r\n  </div>\r\n  <!--内容显示区-->\r\n  <div data-options=\"region:'center'\">\r\n    <div id=\"tt\" class=\"easyui-tabs\" fit=\"true\" border=\"false\" plain=\"true\" style=\"width: 1091px; height: 224px;\">\r\n      <div title=\"Welcome\" style=\"padding:20px;display:none;\">\r\n        tab1\r\n      </div>\r\n    </div>\r\n  </div>\r\n</div>";
},"useData":true,"useBlockParams":true});
templates["page.userManager"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div id=\"table\" style=\"width: 1000px;height:500px;\"></div>";
},"useData":true});
templates["widget.addUser"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:400px\" data-options=\"closed:true,modal:true,border:'thin',buttons:'#dlg-buttons'\">\r\n    <form id=\"fm\" method=\"post\" novalidate style=\"margin:0;padding:20px 50px\">\r\n        <h3>User Information</h3>\r\n        <div style=\"margin-bottom:10px\">\r\n            <input name=\"id\" class=\"easyui-textbox\" required=\"true\" label=\"ID:\" style=\"width:100%\">\r\n        </div>\r\n        <div style=\"margin-bottom:10px\">\r\n            <input name=\"username\" class=\"easyui-textbox\" required=\"true\" label=\"用户名:\" style=\"width:100%\">\r\n        </div>\r\n        <div style=\"margin-bottom:10px\">\r\n            <input name=\"phoneNumber\" class=\"easyui-numberbox\" required=\"true\" label=\"手机号码:\" style=\"width:100%\">\r\n        </div>\r\n        <div style=\"margin-bottom:10px\">\r\n            <input name=\"createTime\" class=\"easyui-datetimebox\" required=\"true\" validType=\"email\" label=\"创建时间:\" style=\"width:100%\">\r\n        </div>\r\n    </form>\r\n</div>\r\n<div id=\"dlg-buttons\">\r\n    <a href=\"javascript:void(0)\" class=\"easyui-linkbutton c6\" iconCls=\"icon-ok\" onclick=\"saveUser()\" style=\"width:90px\">Save</a>\r\n    <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" onclick=\"javascript:$('#dlg').dialog('close')\"\r\n        style=\"width:90px\">Cancel</a>\r\n</div>";
},"useData":true});
templates["widget.addwin"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div>\r\n\r\n\r\n</div>";
},"useData":true});
templates["widget.loginForm"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:400px\" data-options=\"closed:true,modal:true,border:'thin',buttons:'#dlg-buttons'\">\r\n    <form id=\"fm\" method=\"post\" novalidate style=\"margin:0;padding:20px 50px\">\r\n        <h3>欢迎登录</h3>\r\n        <div style=\"margin-bottom:20px\">\r\n            <input name=\"username\" class=\"easyui-textbox\" required=\"true\" label=\"用户名:\" iconWidth=\"28\" style=\"width:100%;height:34px;padding:10px;\">\r\n        </div>\r\n        <div style=\"margin-bottom:20px\">\r\n            <input name=\"password\" class=\"easyui-passwordbox\" required=\"true\" label=\"密码:\" iconWidth=\"28\" style=\"width:100%;height:34px;padding:10px\">\r\n        </div>\r\n        <div style=\"margin-bottom:20px\">\r\n            <input name=\"password\" class=\"easyui-passwordbox\" required=\"true\" label=\"确认密码:\" iconWidth=\"28\" style=\"width:100%;height:34px;padding:10px;display:none\">\r\n        </div>\r\n\r\n    </form>\r\n</div>\r\n<div id=\"dlg-buttons\">\r\n    <a href=\"javascript:void(0)\" class=\"easyui-linkbutton c6\" iconCls=\"icon-ok\" onclick=\"saveUser()\" style=\"width:90px\">登录</a>\r\n    <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" onclick=\"javascript:$('#dlg').dialog('close')\"\r\n        style=\"width:90px\">Cancel</a>\r\n</div>";
},"useData":true});
templates["widget.system.createMenu"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div id=\"createDialog\" class=\"crudDialog\">\r\n    <form id=\"defaultForm\" name=\"defaultForm\" class=\"form-horizontal\">\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">菜单名称</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"menuName\" value=\"\" id=\"menuName\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">url</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"url\" value=\"\" id=\"url\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">菜单描述</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"description\" value=\"\" id=\"description\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </form>\r\n</div>";
},"useData":true});
templates["widget.system.createRole"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div id=\"createDialog\" class=\"crudDialog\">\r\n    <form id=\"defaultForm\" name=\"defaultForm\" class=\"form-horizontal\">\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">角色名称</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"roleName\" value=\"\" id=\"roleName\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">描述信息</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"description\" value=\"\" id=\"description\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </form>\r\n</div>";
},"useData":true});
templates["widget.system.user.changPwd"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div id=\"createDialogchangPwd\" class=\"crudDialog\">\r\n    <form id=\"createDialogchangPwdForm\" name=\"createDialogchangPwdForm\" class=\"form-horizontal\">\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">用户账号</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"username\" value=\"\" id=\"username\" readonly>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group errorChg\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3  control-label\">新密码</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"input-group \">\r\n                    <input type=\"password\" class=\"form-control\" name=\"newPwd\" placeholder=\"请输入新密码\" />\r\n                    <span class=\"input-group-addon openOrClose\"><i class=\"zmdi zmdi-eye-off\"></i></span>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group errorChg\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3  control-label\">确认新密码</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"input-group\">\r\n                    <input type=\"password\" class=\"form-control\" name=\"confirmNewPwd\" placeholder=\"请输入新密码\" />\r\n                    <span class=\"input-group-addon openOrClose\"><i class=\"zmdi zmdi-eye-off\"></i></span>\r\n                </div>\r\n    </form>\r\n</div>";
},"useData":true});
templates["widget.system.user.createUser"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div id=\"createDialog\" class=\"crudDialog\">\r\n    <form id=\"defaultForm\" name=\"defaultForm\" class=\"form-horizontal\">\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">用户账号</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"newusername\" value=\"\" id=\"newusername\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">真实姓名</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"realName\" value=\"\" id=\"realName\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">描述信息</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"description\" value=\"\" id=\"description\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group errorChg\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3  control-label\">用户密码</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"input-group \">\r\n                    <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"请输入密码\" />\r\n                    <span class=\"input-group-addon openOrClose\"><i class=\"zmdi zmdi-eye-off\"></i></span>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">手机号码</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"phoneNumber\" value=\"\" id=\"phoneNumber\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </form>\r\n</div>";
},"useData":true});
templates["widget.system.user.editUser"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div id=\"createDialog\" class=\"crudDialog\">\r\n    <form id=\"defaultForm\" name=\"defaultForm\" class=\"form-horizontal\">\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">用户账号</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"username\" value=\"\" id=\"username\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">真实姓名</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"realName\" value=\"\" id=\"realName\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">描述信息</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"description\" value=\"\" id=\"description\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label class=\"col-lg-3 col-md-3 col-sm-3 control-label\">手机号码</label>\r\n            <div class=\"col-lg-8 col-sm-8 col-md-8\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"text\" class=\"form-control\" name=\"phoneNumber\" value=\"\" id=\"phoneNumber\">\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </form>\r\n</div>";
},"useData":true});
/* jshint ignore:end */
